---

target_env: lab-ses-ipa

cloud_provider: 'gcp'

terraform_project_repo: 'https://github.com/klusters/terraform-gcp-infra'
terraform_project_version: 'multilayer'

terraform_env_vars: {}

terraform_dir: "{{ playbook_dir }}/../../../tf-cdp-cluster-{{ target_env }}"
terraform_layer: 'instances'

terraform_app_name: freeipa
terraform_grp_prefix: cdp
template_inventory: 'inventories/gce_instances.gcp.yml.j2'

inventory_dest: "{{ ansible_inventory_sources[0] }}"

instances_region: "europe-north1"

instance_roles:
  freeipa:
    disk_size_gb: 150
    additional_disks:
    - auto_delete: true
      boot: false
      disk_size_gb: 100
      disk_type: pd-standard
      disk_name: null
      device_name: logs
      mount_path: /var/log
      disk_labels:
        purpose: logs

    source_image: "rocky-linux-9-optimized-gcp"
    source_image_project: "rocky-linux-cloud"

    machine_type: t2d-standard-2

    subnetwork: priv-net

    count: 2
    preemptible: true
    spot: true

    labels:
      createdby: iac
      app: '{{ terraform_app_name }}'
      environment: '{{ target_env }}'
      role: idm
      purpose: idm
      instance_role: freeipa

    tags:
      - openbar

    service_account:
      email: "111378343683-compute@developer.gserviceaccount.com"
      scopes: ["storage-ro"]
