---

- name: Get localhost username
  hosts: localhost
  connection: local

- name: Set OpenVPN server
  hosts: openvpn
  become: true
  gather_facts: true
  pre_tasks:
    - name: Get actual localhost username
      ansible.builtin.set_fact:
        vpn_user: "{{ hostvars['localhost']['ansible_user_id'] }}"

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

  tasks:
    - name: Create openvpn server
      ansible.builtin.include_role:
        name: robertdebock.openvpn
      vars:
        openvpn_role: "server"

    - name: Copy certificates and keys from the server to the client
      ansible.builtin.fetch:
        src: /etc/openvpn/easy-rsa/pki/{{ item }}
        dest: /tmp/{{ item | basename }}
        mode: "0640"
        flat: true
      loop:
        - ca.crt
        - "issued/{{ vpn_user }}.crt"
        - "private/{{ vpn_user }}.key"
        - ta.key

- name: Set OpenVPN client
  hosts: localhost
  connection: local
  become: true
  pre_tasks:
    - name: Get actual localhost username
      ansible.builtin.set_fact:
        vpn_user: "{{ hostvars['localhost']['ansible_user_id'] }}"
      become: false

  tasks:
    - name: Ensure /etc/openvpn/client exist
      ansible.builtin.file:
        path: /etc/openvpn/client
        state: directory
        mode: "0750"
        owner: root
        group: root

    - name: Copy certificates and keys from the server to the client
      ansible.builtin.copy:
        src: /tmp/{{ item }}
        dest: /etc/openvpn/client/{{ item }}
        mode: "0640"
      loop:
        - ca.crt
        - "{{ vpn_user }}.crt"
        - "{{ vpn_user }}.key"
        - ta.key

    - name: Create openvpn client
      ansible.builtin.include_role:
        name: robertdebock.openvpn
      vars:
        openvpn_client_server: "{{ hostvars[groups.openvpn | first]['ansible_host'] }}"
        openvpn_role: "client"
        openvpn_group: nogroup
        openvpn_configuration_directory: /etc/openvpn
