---

krb5_kdc_type: Red Hat IPA
krb5_enc_types: aes256-cts
krb5_realm: LAB.ZLABIA.AFRICA

ipaserver_realm: "{{ krb5_realm }}"
ipaserver_domain: "{{ krb5_domain | default(krb5_realm | lower) }}"

krb5_kdc_admin_user: "admin@{{ krb5_realm }}"
krb5_kdc_admin_password: "{{ ipaadmin_password }}"
krb5_kdc_host: "{{ groups.cdp_idm | first }}"
ipa_ldap_url: "ldaps://{{ groups.cdp_idm | first }}"
