---

- name: Get secrets
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create License file
      ansible.builtin.copy:
        dest: "{{ ansible_inventory_sources[0] }}/../../../licenses/license.txt"
        mode: '644'
        content: "{{ cdp_license }}"
