---

- name: Get secrets
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create secrets file
      ansible.builtin.copy:
        dest: "{{ ansible_inventory_sources[0] }}/group_vars/all/bw_secrets.yml"
        mode: '644'
        content: "{{ bw_secrets | to_nice_yaml }}"

    - name: Create License file
      ansible.builtin.copy:
        dest: "{{ ansible_inventory_sources[0] }}/../../licenses/license.txt"
        mode: '644'
        content: "{{ bw_secrets.cdp_license }}"
