---

- name: Set up Cloudera Manager Server
  hosts: cloudera_manager
  gather_facts: false
  become: true

  tasks:
    - name: Set up Cloudera Manager Server
      ansible.builtin.include_role:
        name: cloudera.cluster.cloudera_manager.server

    - name: Wait for Cloudera Manager Server to come back up
      ansible.builtin.meta: flush_handlers

    - name: "Run role {{ item }}"
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - cloudera.cluster.cloudera_manager.license
        - cloudera.cluster.cloudera_manager.config
        - cloudera.cluster.cloudera_manager.external_auth
        - cloudera.cluster.cloudera_manager.external_account

    - name: Wait for Cloudera Manager Server to come back up
      ansible.builtin.meta: flush_handlers

    - name: "Run role {{ item }}"
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - cloudera.cluster.cloudera_manager.admin_password.set
        - cloudera.cluster.cloudera_manager.api_client
        - cloudera.cluster.cloudera_manager.kerberos
