---

- name: Init infra
  hosts: localhost
  connection: local
  gather_facts: false

  roles:
    - role: cloud-infra
      vars:
        state: present

- name: Check SSH availability
  hosts: all
  gather_facts: false

  tasks:

    - name: Wait for system to become reachable
      ansible.builtin.wait_for_connection:
        timeout: 90
        delay: 15
