---

infra_type: local

update_services: yes

definition_path: "{{ ansible_inventory_sources[0] }}/../../../definitions/"
definition_file: CDPaaS.yml

cdp_security_features:
  kerberos: true
  tls: false
  hdfs_encryption: false

cdp_cluster_name: CDPaaS
cluster_duty_type: heavy_duty
