---

target_env: build-cdp-parcels

cloud_provider: 'gcp'

terraform_project_repo: 'https://github.com/klusters/terraform-gcp-infra'
terraform_project_version: 'multilayer'

terraform_env_vars: {}

terraform_dir: "/tmp/tf-cdp-cluster-{{ target_env }}"
terraform_layer: 'instances'

terraform_grp_prefix: parcels
terraform_app_name: parcels

template_inventory: 'inventories/openvpn_instances.gcp.yml.j2'

inventory_dest: "{{ ansible_inventory_sources[0] }}"

instances_region: "europe-north1"

instances_use_default_sa: true
service_accounts: "{{ hostvars['localhost']['service_accounts'] }}"
instances_default_sa_email: "{{ service_accounts.resources | selectattr('displayName', 'match', '^Compute Engine default service account$') | map(attribute='email') | first }}"

instance_roles:
  build:
    disk_size_gb: 150
    additional_disks:
      - auto_delete: true
        boot: false
        disk_size_gb: 15
        disk_type: pd-ssd
        disk_name: opt-cloudera-parcels
        device_name: opt-cloudera-parcels
        mount_path: /opt/cloudera/parcels
        disk_labels:
          purpose: opt-cloudera-parcels

    source_image: "rhel-8"
    source_image_project: "rhel-cloud"

    machine_type: e2-highcpu-4

    subnetwork: pub-net

    count: 1
    preemptible: true
    spot: true

    labels:
      createdby: iac
      app: '{{ terraform_app_name }}'
      environment: '{{ target_env }}'
      role: build
      purpose: parcels
      instance_role: build

    tags:
      - ssh

    service_account:
      email: "{{ instances_default_sa_email }}"
      scopes: ["storage-rw", "compute-rw"]

    access_config:
      - nat_ip:
        network_tier: PREMIUM