---

repo_download_username: "{{ lookup('community.general.bitwarden_secrets_manager', '32cc3f5e-7c80-4631-b269-b08200614ca7').value }}"
repo_download_password: "{{ lookup('community.general.bitwarden_secrets_manager', '91e539e5-6979-4786-8d34-b08200614e6a').value }}"
