---
collections:

  - name: https://github.com/anisf/cloudera.cluster.git
    type: git
    version: n-ci-lab

  - community.postgresql
  - community.crypto
  - name: community.general
    version: 7.2.1
  - freeipa.ansible_freeipa
  - ansible.posix
  - google.cloud
  - name: klusters.system
    version: 1.2.5
  - name: community.mysql
    version: 3.1.0

roles :
  - name: cloud_infra
    src: git+https://github.com/klusters/ansible-role-cloud_infra.git
    version: '3.1.1'

  - name: cloudera.deploy
    src: git+https://github.com/anisf/cloudera-deploy.git
    version: role

  - name: build_parcels
    src: git+https://github.com/klusters/ansible-role-build_parcels.git
    version: main

  - name: robertdebock.openvpn
    src: git+https://github.com/klusters/ansible-role-openvpn.git
    version: 1.0.0

  - geerlingguy.postgresql
