---

target_env: lab-ses-net

cloud_provider: 'gcp'

terraform_project_repo: 'https://github.com/klusters/terraform-gcp-infra'
terraform_project_version: 'multilayer'

terraform_env_vars: {}

terraform_dir: "{{ playbook_dir }}/../../../tf-cdp-cluster-{{ target_env }}"
terraform_layer: 'fw_rules'

skip_ssh: true
cloud_infra_prepare_inventory: false

fw_rules_project_id: "{{ lookup('env','GCLOUD_PROJECT') }}"
fw_rules:
  - name: open-bar
    description: Allow everything
    direction: INGRESS
    priority: null
    ranges:
      - 10.0.20.0/24
      - 10.0.21.0/24
    source_tags: null
    source_service_accounts: null
    target_tags:
      - openbar
    target_service_accounts: null
    allow:
      - protocol: tcp
        ports: null # all ports
      - protocol: udp
        ports: null # all ports
      - protocol: icmp
        ports: null # all ports
    deny: []
    log_config: null

