---

target_env: lab-n-cdp

cloud_provider: 'gcp'

terraform_project_repo: 'https://github.com/klusters/terraform-gcp-infra'
terraform_project_version: 'multilayer'

terraform_env_vars: {}

terraform_dir: "{{ playbook_dir }}/../../../tf-cdp-cluster-{{ target_env }}"
terraform_layer: 'instances'

terraform_grp_prefix: cdp
terraform_app_name: cdp
template_inventory: 'inventories/cluster_gce_instances.gcp.yml.j2'

inventory_dest: "{{ ansible_inventory_sources[0] }}"

instances_project_region: "europe-north1"

instance_roles:
  utilities:
    disk_size_gb: 50
    additional_disks:
      - auto_delete: true
        boot: false
        disk_size_gb: 50
        disk_type: pd-standard
        disk_name: null
        device_name: logs
        mount_path: /var/log
        disk_labels:
          purpose: logs

      - auto_delete: true
        boot: false
        disk_size_gb: 60
        disk_type: pd-standard
        disk_name: null
        device_name: opt-cloudera
        mount_path: /opt/cloudera
        disk_labels:
          purpose: opt-cloudera

      - auto_delete: true
        boot: false
        disk_size_gb: 20
        disk_type: pd-standard
        disk_name: null
        device_name: data-01
        mount_path: /data/01
        disk_labels:
          purpose: data-01

      - auto_delete: true
        boot: false
        disk_size_gb: 20
        disk_type: pd-standard
        disk_name: null
        device_name: data-02
        mount_path: /data/02
        disk_labels:
          purpose: data-02

    source_image: "rhel-8"
    source_image_project: "rhel-cloud"

    machine_type: n2d-standard-8

    subnetwork: priv-net

    count: 1
    preemptible: true
    spot: true

    labels:
      createdby: iac
      app: '{{ terraform_app_name }}'
      environment: '{{ target_env }}'
      role: utility
      purpose: cluster
      instance_role: utilities

    tags:
      - openbar

    service_account:
      email: "12089038790-compute@developer.gserviceaccount.com"
      scopes: ["storage-ro"]

  masters:
    disk_size_gb: 50
    additional_disks:
      - auto_delete: true
        boot: false
        disk_size_gb: 50
        disk_type: pd-standard
        disk_name: null
        device_name: logs
        mount_path: /var/log
        disk_labels:
          purpose: logs

      - auto_delete: true
        boot: false
        disk_size_gb: 30
        disk_type: pd-standard
        disk_name: null
        device_name: opt-cloudera
        mount_path: /opt/cloudera
        disk_labels:
          purpose: opt-cloudera

      - auto_delete: true
        boot: false
        disk_size_gb: 20
        disk_type: pd-standard
        disk_name: null
        device_name: data-01
        mount_path: /data/01
        disk_labels:
          purpose: data-01

      - auto_delete: true
        boot: false
        disk_size_gb: 20
        disk_type: pd-standard
        disk_name: null
        device_name: data-02
        mount_path: /data/02
        disk_labels:
          purpose: data-02

    source_image: "rhel-8"
    source_image_project: "rhel-cloud"

    machine_type: n2d-standard-4

    subnetwork: priv-net

    count: 3
    preemptible: true
    spot: true

    labels:
      createdby: iac
      app: '{{ terraform_app_name }}'
      environment: '{{ target_env }}'
      role: master
      purpose: cluster
      instance_role: masters

    tags:
      - openbar

    service_account:
      email: "12089038790-compute@developer.gserviceaccount.com"
      scopes: ["storage-ro"]

  edges:
    disk_size_gb: 50
    additional_disks:
      - auto_delete: true
        boot: false
        disk_size_gb: 50
        disk_type: pd-standard
        disk_name: null
        device_name: logs
        mount_path: /var/log
        disk_labels:
          purpose: logs

      - auto_delete: true
        boot: false
        disk_size_gb: 30
        disk_type: pd-standard
        disk_name: null
        device_name: opt-cloudera
        mount_path: /opt/cloudera
        disk_labels:
          purpose: opt-cloudera

      - auto_delete: true
        boot: false
        disk_size_gb: 20
        disk_type: pd-standard
        disk_name: null
        device_name: data-01
        mount_path: /data/01
        disk_labels:
          purpose: data-01

      - auto_delete: true
        boot: false
        disk_size_gb: 20
        disk_type: pd-standard
        disk_name: null
        device_name: data-02
        mount_path: /data/02
        disk_labels:
          purpose: data-02

    source_image: "rhel-8"
    source_image_project: "rhel-cloud"

    machine_type: n2d-standard-4

    subnetwork: priv-net

    count: 1
    preemptible: true
    spot: true

    labels:
      createdby: iac
      app: '{{ terraform_app_name }}'
      environment: '{{ target_env }}'
      role: edge
      purpose: cluster
      instance_role: edges

    tags:
      - openbar

    service_account:
      email: "12089038790-compute@developer.gserviceaccount.com"
      scopes: ["storage-ro"]

  workers:
    disk_size_gb: 50
    additional_disks:
      - auto_delete: true
        boot: false
        disk_size_gb: 50
        disk_type: pd-standard
        disk_name: null
        device_name: logs
        mount_path: /var/log
        disk_labels:
          purpose: logs

      - auto_delete: true
        boot: false
        disk_size_gb: 30
        disk_type: pd-standard
        disk_name: null
        device_name: opt-cloudera
        mount_path: /opt/cloudera
        disk_labels:
          purpose: opt-cloudera

      - auto_delete: true
        boot: false
        disk_size_gb: 20
        disk_type: pd-standard
        disk_name: null
        device_name: data-01
        mount_path: /data/01
        disk_labels:
          purpose: data-01

      - auto_delete: true
        boot: false
        disk_size_gb: 20
        disk_type: pd-standard
        disk_name: null
        device_name: data-02
        mount_path: /data/02
        disk_labels:
          purpose: data-02

    source_image: "rhel-8"
    source_image_project: "rhel-cloud"

    machine_type: n2d-standard-4

    subnetwork: priv-net

    count: 3
    preemptible: true
    spot: true

    labels:
      createdby: iac
      app: '{{ terraform_app_name }}'
      environment: '{{ target_env }}'
      role: worker
      purpose: cluster
      instance_role: workers

    tags:
      - openbar

    service_account:
      email: "12089038790-compute@developer.gserviceaccount.com"
      scopes: ["storage-ro"]

  # newworkers:
  #   disk_size_gb: 50
  #   additional_disks:
  #     - auto_delete: true
  #       boot: false
  #       disk_size_gb: 50
  #       disk_type: pd-standard
  #       disk_name: null
  #       device_name: logs
  #       mount_path: /var/log
  #       disk_labels:
  #         purpose: logs

  #     - auto_delete: true
  #       boot: false
  #       disk_size_gb: 30
  #       disk_type: pd-standard
  #       disk_name: null
  #       device_name: opt-cloudera
  #       mount_path: /opt/cloudera
  #       disk_labels:
  #         purpose: opt-cloudera

  #     - auto_delete: true
  #       boot: false
  #       disk_size_gb: 20
  #       disk_type: pd-standard
  #       disk_name: null
  #       device_name: data-01
  #       mount_path: /data/01
  #       disk_labels:
  #         purpose: data-01

  #     - auto_delete: true
  #       boot: false
  #       disk_size_gb: 20
  #       disk_type: pd-standard
  #       disk_name: null
  #       device_name: data-02
  #       mount_path: /data/02
  #       disk_labels:
  #         purpose: data-02

  #   source_image: "rhel-8"
  #   source_image_project: "rhel-cloud"

  #   machine_type: n2-standard-4

  #   subnetwork: priv-net

  #   count: 2
  #   preemptible: true
  #   spot: true

  #   labels:
  #     createdby: iac
  #     app: '{{ terraform_app_name }}'
  #     environment: '{{ target_env }}'
  #     role: newworker
  #     purpose: cluster
  #     instance_role: newworkers

  #   tags:
  #     - openbar

  #   service_account:
  #     email: "12089038790-compute@developer.gserviceaccount.com"
  #     scopes: ["storage-ro"]
